### ISSUE TITLE
Getting Started Guidance

### ISSUE THREAD

**Issue by DeanGross144** [msdirtbag/MDC-Quickstart#1]
This looks interesting, but I am not quite sure what I should do to evaluate this in my lab. Could you please provide some additional information to help us get started. TIA

**Comment by msdirtbag** [comment]
Great call! Does the updated readme help? https://github.com/msdirtbag/MDC-Quickstart/blob/main/README.md

**Comment by DeanGross144** [comment]
Thanks, that looks like it will get me over the hump
